# -*- coding: utf-8 -*-
# MfgToolLib script
#

Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["CCFLAGS"] = [
    "-O3",
    "-g",
    "-fpermissive",
    "-std=c++11",
    "-Wno-write-strings",
]

dst = "MfgToolLib"

inc = [
    ".",
]

src = [
    "CmdOperation.cpp",
    "ControllerClass.cpp",
    "Device.cpp",
    "DeviceClass.cpp",
    "DeviceManager.cpp",
    "Disk.cpp",
    "DiskDeviceClass.cpp",
    "ExceptionHandle.cpp",
    "HidDevice.cpp",
    "HidDeviceClass.cpp",
    "HubClass.cpp",
    "LogMgr.cpp",
    "MfgToolLib.cpp",
    "MxHidDevice.cpp",
    "MxHidDeviceClass.cpp",
    "MxRomDevice.cpp",
    "MxRomDeviceClass.cpp",
    "ParameterT.cpp",
    "SetupApi.cpp",
    "StApi.cpp",
    "stdafx.cpp",
    "StFwComponent.cpp",
    "StHidApi.cpp",
    "StPitc.cpp",
    "StVersionInfo.cpp",
    "UpdateTransportProtocol.cpp",
    "UsbController.cpp",
    "UsbHub.cpp",
    "UsbPort.cpp",
    "Volume.cpp",
    "VolumeDeviceClass.cpp",
    "libusbVolume.cpp",
    "XMLite.cpp",
]

lib = [
]

env["LIBPATH"] = [
    genv["out"],
]

env["LINKFLAGS"] = [
    "",
]

lib_static = env.StaticLibrary(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("lib_static")
