# -*- coding: utf-8 -*-
# MfgToolCli building script
#

import time
Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["LIBPATH"] = [
    genv["out"],
]

env["CCFLAGS"] = [
    "-O2",
    "-g",
    "-fpermissive",
    "-std=c++11",
    "-Wno-write-strings",
]

env["LINKFLAGS"] = [
]

dst = "MfgToolCli"

inc = [
    ".",
    "../MfgToolLib",
]

src = env.Glob("*.cpp")

lib = [
    "usb-1.0",
    "pthread",
    "stdc++",
    "rt",
    "MfgToolLib",
    "usb-1.0",
    "pthread",
    "stdc++",
    "rt",
]

prog = env.Program(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("prog")
